import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import Dashboard from "../components/Dashboard";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Six Eyes Tech</title>
        <meta name="description" content="Generated by create next app" />
    <meta name="google-site-verification" content="OMBJ6-HQ5nVampDo4WK-jGf4YNpdHUAnIlTM0V4fPqY" />
        <link rel="icon" href="/siXeyes.png" />
      </Head>

      <main>
        <Dashboard />
      </main>
    </div>
  );
}
